
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBziUJNSydlU9IsBY5OCzBNqSOpEbrfTXY',
    appId: '1:17225323324:web:7e4974fc36784cf2e60439',
    messagingSenderId: '17225323324',
    projectId: 'door2doorservices-8c5c9',
    authDomain: 'door2doorservices-8c5c9.firebaseapp.com',
    storageBucket: 'door2doorservices-8c5c9.firebasestorage.app',
    measurementId: 'G-HSLT06RZER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2bm03AiTwhdYltghlLUF1LuZYKXJfc4',
    appId: '1:17225323324:android:5cf6ad2c5a6f127ae60439',
    messagingSenderId: '17225323324',
    projectId: 'door2doorservices-8c5c9',
    storageBucket: 'door2doorservices-8c5c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVrjyqXPp0-_ZmuSjH93aMon8VoCMSC_Y',
    appId: '1:17225323324:ios:c81782f19b2a3a9ee60439',
    messagingSenderId: '17225323324',
    projectId: 'door2doorservices-8c5c9',
    storageBucket: 'door2doorservices-8c5c9.firebasestorage.app',
    iosBundleId: 'com.example.doorToDoorServices',
  );
}
